import { Box, Paper, Typography, List, ListItem, ListItemText } from '@mui/material';
import React from 'react';

function Privacy() {
  return (
    <Box sx={{ m: { sm: 4, md: 10 } }}>
      <Paper elevation={4} sx={{ p: 4 }}>
        <Typography variant="h4" fontWeight="bold" gutterBottom>
          Privacy Policy
        </Typography>
        <Typography paragraph color="text.secondary">
          Last Updated: February 22, 2025
        </Typography>
        <Typography paragraph color="text.secondary">
          This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You, including compliance with the Information Technology Act, 2000 (India) and its associated rules.
        </Typography>
        <Typography paragraph color="text.secondary">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </Typography>

        <SectionTitle title="Interpretation and Definitions" />
        <Typography paragraph color="text.secondary">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
        </Typography>

        <SectionTitle title="Definitions" />
        <List dense>
          {[
            'Account means a unique account created for You to access our Service or parts of our Service.',
            'Affiliate means an entity that controls, is controlled by or is under common control with a party.',
            'Application refers to SafeXcode, the software program provided by the Company.',
            'Company refers to Carshala Services Private Limited, H.no-96, 4th Floor, Pkt-4, Sec-2, Rohini, Delhi, India, 110085.',
            'Cookies are small files placed on Your device by a website, containing details of Your browsing history.',
            'Country: Delhi, India',
            'Device means any device that can access the Service such as a computer, a cell phone, or a digital tablet.',
            'Personal Data is any information that relates to an identified or identifiable individual.',
            'Sensitive Personal Data or Information (SPDI) refers to specific data categories such as passwords, financial information, biometric data, etc.',
            'Service refers to the Application or the Website or both.',
            'Service Provider means any natural or legal person who processes data on behalf of the Company.',
            'Third-party Social Media Service refers to any website or social network where a User can log in to use the Service.',
            'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
            'Website refers to SafeXcode, accessing or using the Service.',
          ].map((text, idx) => (
            <ListItem key={idx} disableGutters>
              <ListItemText primary={text} />
            </ListItem>
          ))}
        </List>

        <SectionTitle title="Collecting and Using Your Personal Data" />
        <Typography paragraph color="text.secondary">
          Types of Data Collected
        </Typography>

        <SectionTitle title="Personal Data" />
        <Typography paragraph color="text.secondary">
          We may ask You to provide Us with personally identifiable information including: First and last name, Email address, Phone number, Address, State, Province, ZIP/Postal code, City, Usage Data
        </Typography>

        <SectionTitle title="Sensitive Personal Data" />
        <Typography paragraph color="text.secondary">
          As per the IT Rules, 2011, we may collect and store sensitive personal data, including but not limited to: Passwords, Financial information (such as bank account or payment details), Biometric information (if applicable), Any other data categorized as sensitive under applicable law.
        </Typography>

        <SectionTitle title="Usage Data" />
        <Typography paragraph color="text.secondary">
          Usage Data is collected automatically when using the Service. This may include: Your IP address, Browser type and version, Pages visited, time and date of visit, Unique device identifiers, Mobile device information.
        </Typography>

        <SectionTitle title="Information from Third-Party Social Media Services" />
        <Typography paragraph color="text.secondary">
          You may create an account using Third-Party Social Media Services like: Google, Facebook, Instagram, Twitter, LinkedIn. If You choose to do so, We may collect information already associated with Your account.
        </Typography>

        <SectionTitle title="Information Collected while Using the Application" />
        <Typography paragraph color="text.secondary">
          With Your permission, We may collect: Location information, Pictures and other media from Your device. You can enable or disable access at any time through Your Device settings.
        </Typography>

        <SectionTitle title="Tracking Technologies and Cookies" />
        <List dense>
          <ListItem><ListItemText primary="Essential Cookies for authentication and fraud prevention" /></ListItem>
          <ListItem><ListItemText primary="Acceptance Cookies to track consent" /></ListItem>
          <ListItem><ListItemText primary="Functionality Cookies to remember user preferences" /></ListItem>
        </List>

        <SectionTitle title="Use of Your Personal Data" />
        <Typography paragraph color="text.secondary">
          The Company may use Personal Data for: Providing and maintaining our Service, Managing Your Account, Performing a contract, Contacting You, Providing offers and updates, Business transfers, Data analysis and improvement of Service.
        </Typography>

        <SectionTitle title="Sharing Your Personal Data" />
        <Typography paragraph color="text.secondary">
          We may share Your data: With Service Providers, For business transfers, With Affiliates, With business partners, With other users (if You interact publicly), With Your consent.
        </Typography>

        <SectionTitle title="Retention of Your Personal Data" />
        <Typography paragraph color="text.secondary">
          We retain Personal Data only as necessary for the purposes stated in this policy, in compliance with the IT Act, 2000 and IT Rules, 2011.
        </Typography>

        <SectionTitle title="Transfer of Your Personal Data" />
        <Typography paragraph color="text.secondary">
          Your information may be transferred and stored in a location outside Your jurisdiction, subject to adequate data protection measures.
        </Typography>

        <SectionTitle title="Deletion of Your Personal Data" />
        <List dense>
          <ListItem><ListItemText primary="Account settings" /></ListItem>
          <ListItem><ListItemText primary="Contacting Us" /></ListItem>
        </List>

        <SectionTitle title="Disclosure of Your Personal Data" />
        <Typography paragraph color="text.secondary">
          We may disclose Personal Data: In business transactions (mergers, acquisitions, etc.), To comply with legal obligations under the IT Act, 2000, To protect the Company's rights.
        </Typography>

        <SectionTitle title="Security of Your Personal Data" />
        <Typography paragraph color="text.secondary">
          We implement reasonable security practices and procedures. While We strive to protect Your data, no method of transmission or storage is 100% secure.
        </Typography>

        <SectionTitle title="Children's Privacy" />
        <Typography paragraph color="text.secondary">
          Our Service does not address children under 13, and We do not knowingly collect data from them.
        </Typography>

        <SectionTitle title="Links to Other Websites" />
        <Typography paragraph color="text.secondary">
          We are not responsible for third-party website privacy policies or practices.
        </Typography>

        <SectionTitle title="Changes to this Privacy Policy" />
        <Typography paragraph color="text.secondary">
          We may update this Privacy Policy periodically. Changes become effective upon posting on this page.
        </Typography>
      </Paper>
    </Box>
  );
}

// Reusable Section Title component
const SectionTitle = ({ title }) => (
  <Typography variant="subtitle1" fontWeight={600} sx={{ mt: 4, mb: 2 }}>
    {title}
  </Typography>
);

export default Privacy;
